/**
 * @file language resources
 * @author atom-yang
 */

export const resources = {
  en: {
    translation: {
      randomNumber: 'Random Number',
      lottery: 'Room Selection Lottery',
      weChatSweep: 'WeChat sweep',
      follow: 'Follow the aelf Offical Accounts',
      order: 'order',
      name: 'name',
      number: 'number',
      introduce:
        'Aelf is an efficient blockchain system that uses cutting-edge design and technology in the IT industry.',
      contactUs: 'contact us',
      aelf: 'Blockchain AELF',
      generationRandomNumber: 'The Generation Plan of Random Number',
      learnMore: 'Learn more',
      generationRandom: 'Random Number Generator',
      minNumber: 'Min',
      minPlaceholder: 'Please enter minimum',
      maxNumber: 'Max',
      maxPlaceholder: 'Please enter maximum',
      generate: 'generate',
      verify: 'Verification',
      random: 'Random Number of Current Round',
      currentBlockHeight: 'Check out the block height of random number information',
      requestBlockHeight: 'The block height when random number is requested',
      randomBlockHeight: 'The block height when random number is generated',
      playId: 'Transaction ID',
      hash: 'Hash Value',
      result: 'Result',
      resultText: 'Click to Generate Random Numbers',
      inputError: 'Please enter the correct number',
      Building: 'Singaporean Splendid Building',
      lotSystem: 'The System of House Selection & Lot Number',
      lotNumber: 'Lot Number',
      commentThanks: 'Thank you for your attention and trust',
      specialNote: 'Special Note: ',
      commentNote:
        'The project is carried out by the Notary Public Office of the Housing Development Board of Singapore.'
        + 'The number is 100, and the number will be randomly selected. The number will be selected in order of this'
        + ' fairness! Shake the whole live broadcast to ensure that the sale of commercial housing is open and fair.',
      commentStart: 'Start Lot',
      beginLot: 'Household Selection Justice',
      beginLotBtn: 'Start',
      selectedResult: 'Lot Result',
      confirm: 'Confirm',
    }
  },
  'zh-CN': {
    translation: {
      randomNumber: '随机数',
      lottery: '购房选房摇号',
      weChatSweep: '微信扫一扫',
      follow: '关注aelf社区公众号',
      order: '序号',
      name: '名字',
      number: '号码',
      introduce: 'aelf是一个真正达到商用标准, 采用了IT行业最前沿的设计和技术的高效区块链系统',
      contactUs: '联系我们',
      aelf: '区块链AELF',
      generationRandomNumber: '随机数生成方案',
      learnMore: '了解更多',
      generationRandom: '随机数生成器',
      minNumber: '最小值',
      minPlaceholder: '请输入最小值',
      maxNumber: '最大值',
      maxPlaceholder: '请输入最大值',
      currentBlockHeight: '查询随机数信息的区块高度',
      requestBlockHeight: '请求随机数时的区块高度',
      randomBlockHeight: '生成随机数的区块高度',
      playId: '交易Id',
      generate: '生 成',
      result: '结 果',
      verify: '验 证',
      random: '本轮随机数',
      blockHeight: '区块高度',
      hash: 'Hash值',
      resultText: '点击生成产生随机数',
      inputError: '请输入正确的数字',
      Building: '新加坡锦绣楼盘',
      lotSystem: '公正选房摇号系统',
      lotNumber: '启动摇号',
      commentThanks: '感谢大家的关注和信任',
      specialNote: '特别说明: ',
      commentNote: '本项目由新加坡建屋发展局公证处进行公正摇号，本次摇号总计100个号，将随机抽取5个号，将以本次公正摇出的顺序号码依次选房！摇号全程直播，确保商品住房销售公开公正公平。',
      commentStart: '开始摇号',
      beginLot: '选房公正摇号',
      beginLotBtn: '点击摇号',
      selectedResult: '摇号结果产生',
      confirm: '确定',
    }
  }
};
