/**
 * @file language resources
 * @author atom-yang
 */

export const resources = {
  en: {
    translation: {
      login: 'Login',
      down: 'Download',
      installExtension: 'Install the Extension',
      createWallet: 'Create a Wallet',
      refreshPage: 'Refresh the Page',
      installPlugInfo1: 'Before you start, make sure you'
        + 'have downloaded and installed NightELF Explorer Extension, and don\'t forget to refresh the page :)',
      installPlugInfo2: 'Please use Chrome or the Explorer are supported for chrome extensions',
      sysName: 'Wheeling System',
      navaelfSysName: 'aelf Wheeling',
      navProjectManage: 'Project Management',
      wheelPro: 'Wheeling Project Notarization',
      applyCreat: 'Apply to Create',
      readAndAgree: 'I have read and agreed to the terms and conditions and refund policy',
      platDisclaimer: 'Platform Disclaimer',
      projectSetting: 'Project Settings',
      baseInfo: 'Wheeling Basic Information',
      dataInfo: 'Wheeling Data Information',
      ruleInfo: 'Wheeling Rules Setting',
      finish: 'Finish',
      wheelDesc: 'Wheeling Description',
      wheelTheme: 'Wheeling Theme',
      wheelSeedNumber: 'Wheeling Seed number',
      dataImport: 'Data Import',
      upload: 'Upload',
      next: 'Finish, Next',
      resultIndexName: 'Results Index Name',
      numOfResult: 'Numbers of Results Index',
      wheelDarwTime: 'Wheeling Draw Time',
      wheelDrawTimes: 'Wheeling Draw Times',
      lotteryWays: 'Lottery Wheeling Ways',
      oneTimeLottle: 'One-Time Lottery Draw',
      multiTimeLottle: 'Multi-Times Lottery Draw',
      manualWheel: 'Manual Wheeling',
      scheduled: 'Scheduled Wheeling',
      successfulCreate: 'Successful Created',
      successfulCreateDesc: 'The project has been created and set. You can view it'
       + ' in project management and change the rules one hour before the start of wheeling draw.',
      projectDetail: 'Project Details',
      wheelCode: 'Status',
      search: 'Search',
      wheelResultNotarization: 'Wheeling Result Notarization',
      requestId: 'Random Number Request ID',
      randomOnChain: 'Random Number on a Chain',
      transactionHash: 'Transaction Hash',
      blockHash: 'Block Hash',
      blockHeight: 'Block Height',
      chainupTime: 'Chain-up Time',
      extendedInfo: 'Extended Evidence Information',
      partNumber: 'Number',
      partName: 'Name',
      partCode: 'Code',
      partStatus: 'Status',
      notarizedLotteryEntriesList: 'Notarized Lottery Entries List',
      idTheme: 'ID/Theme',
      projectId: 'ID',
      createTime: 'Time',
      details: 'Details',
      actions: 'Action',
      open: 'Open',
      close: 'Close',
      delet: 'Delete',
      aelfWheelSystem: 'aelf Notary Wheeling System',
      joinWheel: 'Join in the Wheeling',
      participantsNumber: 'Valid Participants Number',
      indicatorsNumber: 'Number of Indicators',
      startWheel: 'Start',
      order: 'Number',
      name: 'Name',
      code: 'Code',
      clickToWheel: 'Click to Wheel',
      wheelAgain: 'Wheel Again',
      saveWheelResult: 'Save the Wheeling Results',
      newProject: 'New Projects',
      introduce:
        'Aelf is an efficient blockchain system that uses cutting-edge design and technology in the IT industry.',
      contactUs: 'contact us',
      aelf: 'Blockchain AELF',
      request: 'Sending request to blockchain',
      getCurrentBlockHeigh: 'Getting current block height',
      confirmBlockHeight: 'Determining target block height',
      goheight: 'Heading to target block height',
      producttionBlock: 'Production node is producing block',
      complateHash: 'Calculating current Hash value-in',
      complateSign: 'Calculating current signature SIG',
      generateRandom: 'Generating random number',
      gettingRandom: 'Getting random number',
      pleaseInputTheme: 'Please input the theme of lottery wheeling',
      pleaseInputSeed: 'Please input the seed quantity of lottery wheeling',
      pleaseInputNum: 'Please input number',
      pleaseInputResultIndexName: 'Please input the Results Index Name',
      pleaseInputResultIndexNumber: 'Please input the Numbers of Results Index',
      pleaseLessThenSeedNumber: 'Please enter a number less than the seed quantity',
      pleaseInputSeedTime: 'Please input the lottery wheeling time',
      noLimitlottle: 'There is no limit to the times of lottery wheeling, and "lottery wheeling" can be repeated.',
      templateDown: 'Download Template',
      inputNameOrCode: 'Please enter name / code',
      reImport: 'Re import',
      lottery: 'No Wheeling',
      lotteried: 'Wheeled ',
      inputProjectOrId: 'Please enter project ID / theme',
      userCenter: 'Personal Center',
      logout: 'Log out',
      saveQR: 'Save QR code to album'
    }
  },
  'zh-CN': {
    translation: {
      login: '登录',
      down: '下载',
      installExtension: '安装扩展',
      createWallet: '创建一个钱包',
      refreshPage: '刷新页面',
      installPlugInfo1: '在开始之前，请确保已下载安装nightELF Explorer扩展程序，并且不要忘记刷新页面:)',
      installPlugInfo2: '请使用chrome或支持chrome扩展程序的资源管理器',
      sysName: '摇号系统首页及后台',
      navaelfSysName: 'AElf摇号系统',
      navProjectManage: '项目管理',
      wheelPro: '公证摇号项目',
      applyCreat: '申请创建',
      readAndAgree: '我已阅读并同意',
      platDisclaimer: '平台免责声明',
      projectSetting: '项目设置',
      baseInfo: '摇号基本信息',
      dataInfo: '摇号数据信息',
      ruleInfo: '摇号规则设置',
      finish: '完成创建',
      wheelDesc: '摇号说明',
      wheelTheme: '摇号主题',
      wheelSeedNumber: '摇号种子数量',
      dataImport: '数据导入',
      upload: '上传文件',
      next: '填好，下一步',
      resultIndexName: '结果指标名称',
      numOfResult: '结果指标数量',
      wheelDarwTime: '摇号时间',
      wheelDrawTimes: '摇号次数',
      lotteryWays: '摇号方式',
      oneTimeLottle: '一次性摇号中签',
      multiTimeLottle: '多次摇号中签',
      manualWheel: '人工摇号方式',
      scheduled: '定时自动开奖',
      successfulCreate: '创建成功',
      successfulCreateDesc: '项目已创建并完成设置，您可以在【项目管理】中进行查看，项目规则修改，截止摇号开始前一小时',
      projectDetail: '项目详情',
      wheelCode: '摇号状态',
      search: '查询',
      wheelResultNotarization: '摇号结果公证',
      requestId: '随机数Request ID',
      randomOnChain: '本轮链上随机数',
      transactionHash: '交易Hash',
      blockHash: '所在区块hash',
      blockHeight: '所在区块高度',
      chainupTime: '上链时间',
      extendedInfo: '扩展存证信息',
      partNumber: '参与序号',
      partName: '参与人姓名',
      partCode: '参与人编码',
      partStatus: '参与状态',
      notarizedLotteryEntriesList: '现有公证摇号项目列表',
      idTheme: '项目ID/主题',
      projectId: '项目ID',
      createTime: '创建时间',
      details: '详情',
      actions: '操作',
      open: '开启',
      close: '关闭',
      delet: '删除',
      aelfWheelSystem: 'aelf 公证摇号系统',
      joinWheel: '参与摇号',
      participantsNumber: '有序参与摇号编码',
      indicatorsNumber: '指标数量',
      startWheel: '启动摇号',
      order: '序号',
      name: '姓名',
      code: '中签编码',
      clickToWheel: '点击摇号',
      wheelAgain: '返回重新摇号',
      saveWheelResult: '保存摇号结果',
      newProject: '新建项目',
      introduce: 'aelf是一个真正达到商用标准, 采用了IT行业最前沿的设计和技术的高效区块链系统',
      contactUs: '联系我们',
      aelf: '区块链AELF',
      request: '发送请求到区块链上',
      getCurrentBlockHeigh: '正在获取当前区块高度',
      confirmBlockHeight: '正在确定目标区块高度',
      goheight: '正在前往目标区块高度',
      producttionBlock: '生产节点正在生产区块',
      complateHash: '正在计算当前哈希值-in',
      complateSign: '正在计算当前签名-sign',
      generateRandom: '正在生成随机数',
      gettingRandom: '正在获取随机数',
      pleaseInputTheme: '请填写摇号主题',
      pleaseInputSeed: '请填写摇号种子数量',
      pleaseInputNum: '请填写纯数字',
      pleaseInputResultIndexName: '请填写结果指标名称',
      pleaseInputResultIndexNumber: '请填写结果指标数量',
      pleaseLessThenSeedNumber: '请输入小于种子数量',
      pleaseInputSeedTime: '请填写摇号时间',
      noLimitlottle: '不限制摇号次数，可重复摇号',
      templateDown: '模版下载',
      inputNameOrCode: '请输入姓名/编码',
      reImport: '重新导入',
      lottery: '未摇号',
      lotteried: '已摇号',
      inputProjectOrId: '请输入项目ID/主题',
      userCenter: '个人中心',
      logout: '退出登录',
      saveQR: '保存二维码到本地'
    }
  }
};
